import '../models/prefecture.dart';

/// List of Prefectures
final prefectures = [
  Prefecture(
    code: 1,
    name: '北海道',
    short: '北海道',
    en: 'hokkaido',
    hira: 'ほっかいどう',
    kana: 'ホッカイドウ',
  ),
  Prefecture(
    code: 2,
    name: '青森県',
    short: '青森',
    en: 'aomori',
    hira: 'あおもりけん',
    kana: 'アオモリケン',
  ),
  Prefecture(
    code: 3,
    name: '岩手県',
    short: '岩手',
    en: 'iwate',
    hira: 'いわてけん',
    kana: 'イワテケン',
  ),
  Prefecture(
    code: 4,
    name: '宮城県',
    short: '宮城',
    en: 'miyagi',
    hira: 'みやぎけん',
    kana: 'ミヤギケン',
  ),
  Prefecture(
    code: 5,
    name: '秋田県',
    short: '秋田',
    en: 'akita',
    hira: 'あきたけん',
    kana: 'アキタケン',
  ),
  Prefecture(
    code: 6,
    name: '山形県',
    short: '山形',
    en: 'yamagata',
    hira: 'やまがたけん',
    kana: 'ヤマガタケン',
  ),
  Prefecture(
    code: 7,
    name: '福島県',
    short: '福島',
    en: 'fukushima',
    hira: 'ふくしまけん',
    kana: 'フクシマケン',
  ),
  Prefecture(
    code: 8,
    name: '茨城県',
    short: '茨城',
    en: 'ibaraki',
    hira: 'いばらきけん',
    kana: 'イバラキケン',
  ),
  Prefecture(
    code: 9,
    name: '栃木県',
    short: '栃木',
    en: 'tochigi',
    hira: 'とちぎけん',
    kana: 'トチギケン',
  ),
  Prefecture(
    code: 10,
    name: '群馬県',
    short: '群馬',
    en: 'gunma',
    hira: 'ぐんまけん',
    kana: 'グンマケン',
  ),
  Prefecture(
    code: 11,
    name: '埼玉県',
    short: '埼玉',
    en: 'saitama',
    hira: 'さいたまけん',
    kana: 'サイタマケン',
  ),
  Prefecture(
    code: 12,
    name: '千葉県',
    short: '千葉',
    en: 'chiba',
    hira: 'ちばけん',
    kana: 'チバケン',
  ),
  Prefecture(
    code: 13,
    name: '東京都',
    short: '東京',
    en: 'tokyo',
    hira: 'とうきょうと',
    kana: 'トウキョウト',
  ),
  Prefecture(
    code: 14,
    name: '神奈川県',
    short: '神奈川',
    en: 'kanagawa',
    hira: 'かながわけん',
    kana: 'カナガワケン',
  ),
  Prefecture(
    code: 15,
    name: '新潟県',
    short: '新潟',
    en: 'niigata',
    hira: 'にいがたけん',
    kana: 'ニイガタケン',
  ),
  Prefecture(
    code: 16,
    name: '富山県',
    short: '富山',
    en: 'toyama',
    hira: 'とやまけん',
    kana: 'トヤマケン',
  ),
  Prefecture(
    code: 17,
    name: '石川県',
    short: '石川',
    en: 'ishikawa',
    hira: 'いしかわけん',
    kana: 'イシカワケン',
  ),
  Prefecture(
    code: 18,
    name: '福井県',
    short: '福井',
    en: 'fukui',
    hira: 'ふくいけん',
    kana: 'フクイケン',
  ),
  Prefecture(
    code: 19,
    name: '山梨県',
    short: '山梨',
    en: 'yamanashi',
    hira: 'やまなしけん',
    kana: 'ヤマナシケン',
  ),
  Prefecture(
    code: 20,
    name: '長野県',
    short: '長野',
    en: 'nagano',
    hira: 'ながのけん',
    kana: 'ナガノケン',
  ),
  Prefecture(
    code: 21,
    name: '岐阜県',
    short: '岐阜',
    en: 'gifu',
    hira: 'ぎふけん',
    kana: 'ギフケン',
  ),
  Prefecture(
    code: 22,
    name: '静岡県',
    short: '静岡',
    en: 'shizuoka',
    hira: 'しずおかけん',
    kana: 'シズオカケン',
  ),
  Prefecture(
    code: 23,
    name: '愛知県',
    short: '愛知',
    en: 'aichi',
    hira: 'あいちけん',
    kana: 'アイチケン',
  ),
  Prefecture(
    code: 24,
    name: '三重県',
    short: '三重',
    en: 'mie',
    hira: 'みえけん',
    kana: 'ミエケン',
  ),
  Prefecture(
    code: 25,
    name: '滋賀県',
    short: '滋賀',
    en: 'shiga',
    hira: 'しがけん',
    kana: 'シガケン',
  ),
  Prefecture(
    code: 26,
    name: '京都府',
    short: '京都',
    en: 'kyoto',
    hira: 'きょうとふ',
    kana: 'キョウトフ',
  ),
  Prefecture(
    code: 27,
    name: '大阪府',
    short: '大阪',
    en: 'osaka',
    hira: 'おおさかふ',
    kana: 'オオサカフ',
  ),
  Prefecture(
    code: 28,
    name: '兵庫県',
    short: '兵庫',
    en: 'hyogo',
    hira: 'ひょうごけん',
    kana: 'ヒョウゴケン',
  ),
  Prefecture(
    code: 29,
    name: '奈良県',
    short: '奈良',
    en: 'nara',
    hira: 'ならけん',
    kana: 'ナラケン',
  ),
  Prefecture(
    code: 30,
    name: '和歌山県',
    short: '和歌山',
    en: 'wakayama',
    hira: 'わかやまけん',
    kana: 'ワカヤマケン',
  ),
  Prefecture(
    code: 31,
    name: '鳥取県',
    short: '鳥取',
    en: 'tottori',
    hira: 'とっとりけん',
    kana: 'トットリケン',
  ),
  Prefecture(
    code: 32,
    name: '島根県',
    short: '島根',
    en: 'shimane',
    hira: 'しまねけん',
    kana: 'シマネケン',
  ),
  Prefecture(
    code: 33,
    name: '岡山県',
    short: '岡山',
    en: 'okayama',
    hira: 'おかやまけん',
    kana: 'オカヤマケン',
  ),
  Prefecture(
    code: 34,
    name: '広島県',
    short: '広島',
    en: 'hiroshima',
    hira: 'ひろしまけん',
    kana: 'ヒロシマケン',
  ),
  Prefecture(
    code: 35,
    name: '山口県',
    short: '山口',
    en: 'yamaguchi',
    hira: 'やまぐちけん',
    kana: 'ヤマグチケン',
  ),
  Prefecture(
    code: 36,
    name: '徳島県',
    short: '徳島',
    en: 'tokushima',
    hira: 'とくしまけん',
    kana: 'トクシマケン',
  ),
  Prefecture(
    code: 37,
    name: '香川県',
    short: '香川',
    en: 'kagawa',
    hira: 'かがわけん',
    kana: 'カガワケン',
  ),
  Prefecture(
    code: 38,
    name: '愛媛県',
    short: '愛媛',
    en: 'ehime',
    hira: 'えひめけん',
    kana: 'エヒメケン',
  ),
  Prefecture(
    code: 39,
    name: '高知県',
    short: '高知',
    en: 'kochi',
    hira: 'こうちけん',
    kana: 'コウチケン',
  ),
  Prefecture(
    code: 40,
    name: '福岡県',
    short: '福岡',
    en: 'fukuoka',
    hira: 'ふくおかけん',
    kana: 'フクオカケン',
  ),
  Prefecture(
    code: 41,
    name: '佐賀県',
    short: '佐賀',
    en: 'saga',
    hira: 'さがけん',
    kana: 'サガケン',
  ),
  Prefecture(
    code: 42,
    name: '長崎県',
    short: '長崎',
    en: 'nagasaki',
    hira: 'ながさきけん',
    kana: 'ナガサキケン',
  ),
  Prefecture(
    code: 43,
    name: '熊本県',
    short: '熊本',
    en: 'kumamoto',
    hira: 'くまもとけん',
    kana: 'クマモトケン',
  ),
  Prefecture(
    code: 44,
    name: '大分県',
    short: '大分',
    en: 'oita',
    hira: 'おおいたけん',
    kana: 'オオイタケン',
  ),
  Prefecture(
    code: 45,
    name: '宮崎県',
    short: '宮崎',
    en: 'miyazaki',
    hira: 'みやざきけん',
    kana: 'ミヤザキケン',
  ),
  Prefecture(
    code: 46,
    name: '鹿児島県',
    short: '鹿児島',
    en: 'kagoshima',
    hira: 'かごしまけん',
    kana: 'カゴシマケン',
  ),
  Prefecture(
    code: 47,
    name: '沖縄県',
    short: '沖縄',
    en: 'okinawa',
    hira: 'おきなわけん',
    kana: 'オキナワケン',
  ),
];
